import { NextRequest, NextResponse } from 'next/server';
import { createAdminClient } from '@/lib/supabase/admin';
import { sendTelegramMessage } from '@/lib/telegram';

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
// SEC-HIGH-2: token is 8 chars from the connect-token alphabet (generated by generateTelegramConnectToken)
const TOKEN_RE = /^[A-Z2-9]{8}$/;

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const message = body?.message;
    if (!message?.text || !message?.chat?.id) return NextResponse.json({ ok: true });

    const text: string = message.text;
    const chatId: number = message.chat.id;

    if (!text.startsWith('/start')) return NextResponse.json({ ok: true });

    const param = text.split(' ')[1]?.trim();
    if (!param) return NextResponse.json({ ok: true });

    const admin = createAdminClient();

    if (UUID_RE.test(param)) {
      // ── Client: param = profiles.id (UUID) — unchanged ───────────
      const { error } = await admin
        .from('profiles')
        .update({ telegram_chat_id: String(chatId) })
        .eq('id', param);

      if (!error) {
        await sendTelegramMessage(
          String(chatId),
          '✅ Ваш акаунт успішно підключено до bookit! Тепер ви будете отримувати тут сповіщення.',
        );
      }
    } else if (TOKEN_RE.test(param)) {
      // ── Master: param = telegram_connect_token (one-time, from settings) ──
      // SEC-HIGH-2: atomic UPDATE+clear — token consumed in one query, no replay possible
      const { data: master, error } = await admin
        .from('master_profiles')
        .update({ telegram_chat_id: String(chatId), telegram_connect_token: null })
        .eq('telegram_connect_token', param)
        .select('id')
        .single();

      if (!error && master) {
        await sendTelegramMessage(
          String(chatId),
          '✅ Ваш акаунт майстра успішно підключено до bookit! Тепер ви будете отримувати тут сповіщення про нові записи.',
        );
      }
      // If no master found for token — silently ignore (token expired or already used)
    }

    return NextResponse.json({ ok: true });
  } catch {
    // Never return 500 — Telegram would spam retries
    return NextResponse.json({ ok: true });
  }
}
